baseURL = "https://rfrost.xyz"
title = "Richard Frost"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Richard Frost"
description = "Head of Interactive & Immersive at Pilbrow & Partners"
keywords = "blog,developer,personal"
info = ['Head of Interactive & Immersive at Pilbrow & Partners']

positiontitle = "Head of Interactive & Immersive"
positionorganisation = "Pilbrow & Partners"
positionurl = "https://www.pilbrowandpartners.com/"

avatarURL = "images/rfrost_profile@256.png"
footerContent = '<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA</a> | <a href="/privacy/">Privacy</a>'
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = true
since = 2018
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/rdfrost/rfrost-xyz/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = ["css/coder-extra.css"]
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = [
	"'self'",
	"https://fonts.gstatic.com",
	"https://cdn.jsdelivr.net/"
]
formaction = ["'self'"]
framesrc = [
	"'self'",
	"vimeo.com",
	"*.vimeo.com"
]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
	"'self'",
	"'unsafe-inline'",
	"https://fonts.googleapis.com/",
	"https://cdn.jsdelivr.net/"
]
scriptsrc = [
	"'self'",
	"'unsafe-inline'",
	"vimeo.com",
	"*.vimeo.com",
	"https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSourceoverhand oval gazing impurity onboard
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 1
url = "https://www.linkedin.com/in/rfrost-xyz"

[[params.social]]
name = "GitHub"
icon = "fa fa-github"
weight = 2
url = "https://github.com/rdfrost/"

[[params.social]]
name = "IMDB"
icon = "fa fa-imdb"
weight = 3
url = "https://www.imdb.com/name/nm9553938/?ref_=ttfc_fc_cr82"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Reel"
weight = 2
url = "reel/"

[[languages.en.menu.main]]
name = "Posts"
weight = 3
url = "posts/"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
